error: 
    status - 500 
    message - SyntaxError: Unexpected string in JSON at position 32
    at JSON.parse (<anonymous>)
    at parse (C:\Urmila data\data\WorkSpace\FundooProject\FundooNotes\fundoo_notes\node_modules\body-parser\lib\types\json.js:89:19)
    at C:\Urmila data\data\WorkSpace\FundooProject\FundooNotes\fundoo_notes\node_modules\body-parser\lib\read.js:128:18
    at AsyncResource.runInAsyncScope (node:async_hooks:202:9)
    at invokeCallback (C:\Urmila data\data\WorkSpace\FundooProject\FundooNotes\fundoo_notes\node_modules\raw-body\index.js:231:16)
    at done (C:\Urmila data\data\WorkSpace\FundooProject\FundooNotes\fundoo_notes\node_modules\raw-body\index.js:220:7)
    at IncomingMessage.onEnd (C:\Urmila data\data\WorkSpace\FundooProject\FundooNotes\fundoo_notes\node_modules\raw-body\index.js:280:7)
    at IncomingMessage.emit (node:events:539:35)
    at IncomingMessage.emit (node:domain:475:12)
    at endReadableNT (node:internal/streams/readable:1345:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) 
    url - /api/users 
    method - POST 
    IP - ::1
   {"timestamp":"2022-08-03T14:37:30.590Z"}
error: 
    status - 500 
    message - TypeError: console.error is not a constructor
    at _callee$ (C:\Urmila data\data\WorkSpace\FundooProject\FundooNotes\fundoo_notes\src\services\/user.service.js:12:11)
    at tryCatch (C:\Urmila data\data\WorkSpace\FundooProject\FundooNotes\fundoo_notes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (C:\Urmila data\data\WorkSpace\FundooProject\FundooNotes\fundoo_notes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (C:\Urmila data\data\WorkSpace\FundooProject\FundooNotes\fundoo_notes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (C:\Urmila data\data\WorkSpace\FundooProject\FundooNotes\fundoo_notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Urmila data\data\WorkSpace\FundooProject\FundooNotes\fundoo_notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
    url - /api/v1/users 
    method - POST 
    IP - ::1
   {"timestamp":"2022-08-03T14:56:02.045Z"}
error: 
    status - 500 
    message - ReferenceError: error is not defined
    at _callee$ (C:\Urmila data\data\WorkSpace\FundooProject\FundooNotes\fundoo_notes\src\services\/user.service.js:4:34)
    at tryCatch (C:\Urmila data\data\WorkSpace\FundooProject\FundooNotes\fundoo_notes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (C:\Urmila data\data\WorkSpace\FundooProject\FundooNotes\fundoo_notes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (C:\Urmila data\data\WorkSpace\FundooProject\FundooNotes\fundoo_notes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (C:\Urmila data\data\WorkSpace\FundooProject\FundooNotes\fundoo_notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Urmila data\data\WorkSpace\FundooProject\FundooNotes\fundoo_notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
    url - /api/v1/users 
    method - POST 
    IP - ::1
   {"timestamp":"2022-08-03T14:56:33.740Z"}
error: 
    status - 500 
    message - ValidationError: User validation failed: lastName: Path `lastName` is required., firstName: Path `firstName` is required.
    at model.Document.invalidate (C:\Urmila data\data\WorkSpace\FundooProject\FundooNotes\fundoo_notes\node_modules\mongoose\lib\document.js:2782:32)
    at C:\Urmila data\data\WorkSpace\FundooProject\FundooNotes\fundoo_notes\node_modules\mongoose\lib\document.js:2574:17
    at C:\Urmila data\data\WorkSpace\FundooProject\FundooNotes\fundoo_notes\node_modules\mongoose\lib\schematype.js:1273:9
    at processTicksAndRejections (node:internal/process/task_queues:78:11) 
    url - /api/v1/users 
    method - POST 
    IP - ::1
   {"timestamp":"2022-08-03T15:07:08.184Z"}
error: 
    status - 500 
    message - ValidationError: "firstName" is required 
    url - /api/v1/users 
    method - POST 
    IP - ::1
   {"timestamp":"2022-08-03T15:07:51.748Z"}
error: 
    status - 500 
    message - ValidationError: "firstName" is required 
    url - /api/v1/login 
    method - POST 
    IP - ::1
   {"timestamp":"2022-08-04T04:35:38.842Z"}
error: 
    status - 500 
    message - ValidationError: "firstName" is required 
    url - /api/v1/users 
    method - POST 
    IP - ::1
   {"timestamp":"2022-08-04T04:37:24.534Z"}
error: uncaughtException: error is not defined
ReferenceError: error is not defined
    at _callee3$ (C:\Urmila data\data\WorkSpace\FundooProject\FundooNotes\fundoo_notes\src\controllers\/user.controller.js:59:19)
    at tryCatch (C:\Urmila data\data\WorkSpace\FundooProject\FundooNotes\fundoo_notes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (C:\Urmila data\data\WorkSpace\FundooProject\FundooNotes\fundoo_notes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (C:\Urmila data\data\WorkSpace\FundooProject\FundooNotes\fundoo_notes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (C:\Urmila data\data\WorkSpace\FundooProject\FundooNotes\fundoo_notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Urmila data\data\WorkSpace\FundooProject\FundooNotes\fundoo_notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {"date":"Thu Aug 04 2022 10:07:40 GMT+0530 (India Standard Time)","error":{},"exception":true,"os":{"loadavg":[0,0,0],"uptime":426508},"process":{"argv":["node","C:\\Urmila data\\data\\WorkSpace\\FundooProject\\FundooNotes\\fundoo_notes\\src\\index.js"],"cwd":"C:\\Urmila data\\data\\WorkSpace\\FundooProject\\FundooNotes\\fundoo_notes","execPath":"C:\\Program Files\\nodejs\\node.exe","gid":null,"memoryUsage":{"arrayBuffers":18301162,"external":19972479,"heapTotal":49102848,"heapUsed":44315264,"rss":81362944},"pid":16244,"uid":null,"version":"v16.15.1"},"stack":"ReferenceError: error is not defined\n    at _callee3$ (C:\\Urmila data\\data\\WorkSpace\\FundooProject\\FundooNotes\\fundoo_notes\\src\\controllers\\/user.controller.js:59:19)\n    at tryCatch (C:\\Urmila data\\data\\WorkSpace\\FundooProject\\FundooNotes\\fundoo_notes\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:86:17)\n    at Generator._invoke (C:\\Urmila data\\data\\WorkSpace\\FundooProject\\FundooNotes\\fundoo_notes\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:66:24)\n    at Generator.next (C:\\Urmila data\\data\\WorkSpace\\FundooProject\\FundooNotes\\fundoo_notes\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:117:21)\n    at asyncGeneratorStep (C:\\Urmila data\\data\\WorkSpace\\FundooProject\\FundooNotes\\fundoo_notes\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:3:24)\n    at _next (C:\\Urmila data\\data\\WorkSpace\\FundooProject\\FundooNotes\\fundoo_notes\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:25:9)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)","timestamp":"2022-08-04T04:37:40.626Z","trace":[{"column":19,"file":"C:\\Urmila data\\data\\WorkSpace\\FundooProject\\FundooNotes\\fundoo_notes\\src\\controllers\\/user.controller.js","function":"_callee3$","line":59,"method":null,"native":false},{"column":17,"file":"C:\\Urmila data\\data\\WorkSpace\\FundooProject\\FundooNotes\\fundoo_notes\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js","function":"tryCatch","line":86,"method":null,"native":false},{"column":24,"file":"C:\\Urmila data\\data\\WorkSpace\\FundooProject\\FundooNotes\\fundoo_notes\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js","function":"Generator._invoke","line":66,"method":"_invoke","native":false},{"column":21,"file":"C:\\Urmila data\\data\\WorkSpace\\FundooProject\\FundooNotes\\fundoo_notes\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js","function":"Generator.next","line":117,"method":"next","native":false},{"column":24,"file":"C:\\Urmila data\\data\\WorkSpace\\FundooProject\\FundooNotes\\fundoo_notes\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js","function":"asyncGeneratorStep","line":3,"method":null,"native":false},{"column":9,"file":"C:\\Urmila data\\data\\WorkSpace\\FundooProject\\FundooNotes\\fundoo_notes\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js","function":"_next","line":25,"method":null,"native":false},{"column":5,"file":"node:internal/process/task_queues","function":"processTicksAndRejections","line":96,"method":null,"native":false}]}
error: uncaughtException: error is not defined
ReferenceError: error is not defined
    at _callee3$ (C:\Urmila data\data\WorkSpace\FundooProject\FundooNotes\fundoo_notes\src\controllers\/user.controller.js:59:19)
    at tryCatch (C:\Urmila data\data\WorkSpace\FundooProject\FundooNotes\fundoo_notes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (C:\Urmila data\data\WorkSpace\FundooProject\FundooNotes\fundoo_notes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.throw (C:\Urmila data\data\WorkSpace\FundooProject\FundooNotes\fundoo_notes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (C:\Urmila data\data\WorkSpace\FundooProject\FundooNotes\fundoo_notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _throw (C:\Urmila data\data\WorkSpace\FundooProject\FundooNotes\fundoo_notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:29:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {"date":"Thu Aug 04 2022 10:08:47 GMT+0530 (India Standard Time)","error":{},"exception":true,"os":{"loadavg":[0,0,0],"uptime":426576},"process":{"argv":["node","C:\\Urmila data\\data\\WorkSpace\\FundooProject\\FundooNotes\\fundoo_notes\\src\\index.js"],"cwd":"C:\\Urmila data\\data\\WorkSpace\\FundooProject\\FundooNotes\\fundoo_notes","execPath":"C:\\Program Files\\nodejs\\node.exe","gid":null,"memoryUsage":{"arrayBuffers":18901039,"external":22271527,"heapTotal":79249408,"heapUsed":50480392,"rss":113565696},"pid":28996,"uid":null,"version":"v16.15.1"},"stack":"ReferenceError: error is not defined\n    at _callee3$ (C:\\Urmila data\\data\\WorkSpace\\FundooProject\\FundooNotes\\fundoo_notes\\src\\controllers\\/user.controller.js:59:19)\n    at tryCatch (C:\\Urmila data\\data\\WorkSpace\\FundooProject\\FundooNotes\\fundoo_notes\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:86:17)\n    at Generator._invoke (C:\\Urmila data\\data\\WorkSpace\\FundooProject\\FundooNotes\\fundoo_notes\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:66:24)\n    at Generator.throw (C:\\Urmila data\\data\\WorkSpace\\FundooProject\\FundooNotes\\fundoo_notes\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:117:21)\n    at asyncGeneratorStep (C:\\Urmila data\\data\\WorkSpace\\FundooProject\\FundooNotes\\fundoo_notes\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:3:24)\n    at _throw (C:\\Urmila data\\data\\WorkSpace\\FundooProject\\FundooNotes\\fundoo_notes\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:29:9)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)","timestamp":"2022-08-04T04:38:47.850Z","trace":[{"column":19,"file":"C:\\Urmila data\\data\\WorkSpace\\FundooProject\\FundooNotes\\fundoo_notes\\src\\controllers\\/user.controller.js","function":"_callee3$","line":59,"method":null,"native":false},{"column":17,"file":"C:\\Urmila data\\data\\WorkSpace\\FundooProject\\FundooNotes\\fundoo_notes\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js","function":"tryCatch","line":86,"method":null,"native":false},{"column":24,"file":"C:\\Urmila data\\data\\WorkSpace\\FundooProject\\FundooNotes\\fundoo_notes\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js","function":"Generator._invoke","line":66,"method":"_invoke","native":false},{"column":21,"file":"C:\\Urmila data\\data\\WorkSpace\\FundooProject\\FundooNotes\\fundoo_notes\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js","function":"Generator.throw","line":117,"method":"throw","native":false},{"column":24,"file":"C:\\Urmila data\\data\\WorkSpace\\FundooProject\\FundooNotes\\fundoo_notes\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js","function":"asyncGeneratorStep","line":3,"method":null,"native":false},{"column":9,"file":"C:\\Urmila data\\data\\WorkSpace\\FundooProject\\FundooNotes\\fundoo_notes\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js","function":"_throw","line":29,"method":null,"native":false},{"column":5,"file":"node:internal/process/task_queues","function":"processTicksAndRejections","line":96,"method":null,"native":false}]}
error: uncaughtException: error is not defined
ReferenceError: error is not defined
    at _callee2$ (C:\Urmila data\data\WorkSpace\FundooProject\FundooNotes\fundoo_notes\src\controllers\/user.controller.js:39:19)
    at tryCatch (C:\Urmila data\data\WorkSpace\FundooProject\FundooNotes\fundoo_notes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (C:\Urmila data\data\WorkSpace\FundooProject\FundooNotes\fundoo_notes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (C:\Urmila data\data\WorkSpace\FundooProject\FundooNotes\fundoo_notes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (C:\Urmila data\data\WorkSpace\FundooProject\FundooNotes\fundoo_notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Urmila data\data\WorkSpace\FundooProject\FundooNotes\fundoo_notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {"date":"Thu Aug 04 2022 10:13:25 GMT+0530 (India Standard Time)","error":{},"exception":true,"os":{"loadavg":[0,0,0],"uptime":426853},"process":{"argv":["node","C:\\Urmila data\\data\\WorkSpace\\FundooProject\\FundooNotes\\fundoo_notes\\src\\index.js"],"cwd":"C:\\Urmila data\\data\\WorkSpace\\FundooProject\\FundooNotes\\fundoo_notes","execPath":"C:\\Program Files\\nodejs\\node.exe","gid":null,"memoryUsage":{"arrayBuffers":18301436,"external":19965808,"heapTotal":48054272,"heapUsed":44114760,"rss":80977920},"pid":25620,"uid":null,"version":"v16.15.1"},"stack":"ReferenceError: error is not defined\n    at _callee2$ (C:\\Urmila data\\data\\WorkSpace\\FundooProject\\FundooNotes\\fundoo_notes\\src\\controllers\\/user.controller.js:39:19)\n    at tryCatch (C:\\Urmila data\\data\\WorkSpace\\FundooProject\\FundooNotes\\fundoo_notes\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:86:17)\n    at Generator._invoke (C:\\Urmila data\\data\\WorkSpace\\FundooProject\\FundooNotes\\fundoo_notes\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:66:24)\n    at Generator.next (C:\\Urmila data\\data\\WorkSpace\\FundooProject\\FundooNotes\\fundoo_notes\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:117:21)\n    at asyncGeneratorStep (C:\\Urmila data\\data\\WorkSpace\\FundooProject\\FundooNotes\\fundoo_notes\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:3:24)\n    at _next (C:\\Urmila data\\data\\WorkSpace\\FundooProject\\FundooNotes\\fundoo_notes\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:25:9)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)","timestamp":"2022-08-04T04:43:25.361Z","trace":[{"column":19,"file":"C:\\Urmila data\\data\\WorkSpace\\FundooProject\\FundooNotes\\fundoo_notes\\src\\controllers\\/user.controller.js","function":"_callee2$","line":39,"method":null,"native":false},{"column":17,"file":"C:\\Urmila data\\data\\WorkSpace\\FundooProject\\FundooNotes\\fundoo_notes\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js","function":"tryCatch","line":86,"method":null,"native":false},{"column":24,"file":"C:\\Urmila data\\data\\WorkSpace\\FundooProject\\FundooNotes\\fundoo_notes\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js","function":"Generator._invoke","line":66,"method":"_invoke","native":false},{"column":21,"file":"C:\\Urmila data\\data\\WorkSpace\\FundooProject\\FundooNotes\\fundoo_notes\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js","function":"Generator.next","line":117,"method":"next","native":false},{"column":24,"file":"C:\\Urmila data\\data\\WorkSpace\\FundooProject\\FundooNotes\\fundoo_notes\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js","function":"asyncGeneratorStep","line":3,"method":null,"native":false},{"column":9,"file":"C:\\Urmila data\\data\\WorkSpace\\FundooProject\\FundooNotes\\fundoo_notes\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js","function":"_next","line":25,"method":null,"native":false},{"column":5,"file":"node:internal/process/task_queues","function":"processTicksAndRejections","line":96,"method":null,"native":false}]}
error: 
    status - 500 
    message - ValidationError: "firstName" is required 
    url - /api/v1/login 
    method - POST 
    IP - ::1
   {"timestamp":"2022-08-04T04:55:21.025Z"}
error: 
    status - 500 
    message - ValidationError: "firstName" is required 
    url - /api/v1/login 
    method - POST 
    IP - ::1
   {"timestamp":"2022-08-04T04:55:38.929Z"}
error: 
    status - 500 
    message - ValidationError: "firstName" is required 
    url - /api/v1/login 
    method - POST 
    IP - ::1
   {"timestamp":"2022-08-04T04:59:26.961Z"}
error: 
    status - 500 
    message - ValidationError: "firstName" is required 
    url - /api/v1/login 
    method - POST 
    IP - ::1
   {"timestamp":"2022-08-04T04:59:36.496Z"}
error: uncaughtException: error is not defined
ReferenceError: error is not defined
    at _callee2$ (C:\Urmila data\data\WorkSpace\FundooProject\FundooNotes\fundoo_notes\src\controllers\/user.controller.js:39:19)
    at tryCatch (C:\Urmila data\data\WorkSpace\FundooProject\FundooNotes\fundoo_notes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (C:\Urmila data\data\WorkSpace\FundooProject\FundooNotes\fundoo_notes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.throw (C:\Urmila data\data\WorkSpace\FundooProject\FundooNotes\fundoo_notes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (C:\Urmila data\data\WorkSpace\FundooProject\FundooNotes\fundoo_notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _throw (C:\Urmila data\data\WorkSpace\FundooProject\FundooNotes\fundoo_notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:29:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {"date":"Thu Aug 04 2022 10:43:24 GMT+0530 (India Standard Time)","error":{},"exception":true,"os":{"loadavg":[0,0,0],"uptime":428652},"process":{"argv":["node","C:\\Urmila data\\data\\WorkSpace\\FundooProject\\FundooNotes\\fundoo_notes\\src\\index.js"],"cwd":"C:\\Urmila data\\data\\WorkSpace\\FundooProject\\FundooNotes\\fundoo_notes","execPath":"C:\\Program Files\\nodejs\\node.exe","gid":null,"memoryUsage":{"arrayBuffers":18307751,"external":19987133,"heapTotal":48840704,"heapUsed":44684528,"rss":81936384},"pid":32436,"uid":null,"version":"v16.15.1"},"stack":"ReferenceError: error is not defined\n    at _callee2$ (C:\\Urmila data\\data\\WorkSpace\\FundooProject\\FundooNotes\\fundoo_notes\\src\\controllers\\/user.controller.js:39:19)\n    at tryCatch (C:\\Urmila data\\data\\WorkSpace\\FundooProject\\FundooNotes\\fundoo_notes\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:86:17)\n    at Generator._invoke (C:\\Urmila data\\data\\WorkSpace\\FundooProject\\FundooNotes\\fundoo_notes\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:66:24)\n    at Generator.throw (C:\\Urmila data\\data\\WorkSpace\\FundooProject\\FundooNotes\\fundoo_notes\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:117:21)\n    at asyncGeneratorStep (C:\\Urmila data\\data\\WorkSpace\\FundooProject\\FundooNotes\\fundoo_notes\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:3:24)\n    at _throw (C:\\Urmila data\\data\\WorkSpace\\FundooProject\\FundooNotes\\fundoo_notes\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:29:9)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)","timestamp":"2022-08-04T05:13:24.053Z","trace":[{"column":19,"file":"C:\\Urmila data\\data\\WorkSpace\\FundooProject\\FundooNotes\\fundoo_notes\\src\\controllers\\/user.controller.js","function":"_callee2$","line":39,"method":null,"native":false},{"column":17,"file":"C:\\Urmila data\\data\\WorkSpace\\FundooProject\\FundooNotes\\fundoo_notes\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js","function":"tryCatch","line":86,"method":null,"native":false},{"column":24,"file":"C:\\Urmila data\\data\\WorkSpace\\FundooProject\\FundooNotes\\fundoo_notes\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js","function":"Generator._invoke","line":66,"method":"_invoke","native":false},{"column":21,"file":"C:\\Urmila data\\data\\WorkSpace\\FundooProject\\FundooNotes\\fundoo_notes\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js","function":"Generator.throw","line":117,"method":"throw","native":false},{"column":24,"file":"C:\\Urmila data\\data\\WorkSpace\\FundooProject\\FundooNotes\\fundoo_notes\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js","function":"asyncGeneratorStep","line":3,"method":null,"native":false},{"column":9,"file":"C:\\Urmila data\\data\\WorkSpace\\FundooProject\\FundooNotes\\fundoo_notes\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js","function":"_throw","line":29,"method":null,"native":false},{"column":5,"file":"node:internal/process/task_queues","function":"processTicksAndRejections","line":96,"method":null,"native":false}]}
